'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { useAuth } from '@/lib/contexts/AuthContext';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import Modal from '@/components/ui/Modal';
import Badge from '@/components/ui/Badge';
import LoadingSpinner from '@/components/ui/LoadingSpinner';
import { useToast } from '@/components/ui/ToastContainer';
import {
  getUserById,
  addUserAddress,
} from '@/services/user-service';
import { User, Address } from '@/types/user';
import { geocodeAddress } from '@/lib/utils/geocoding';
import {
  MapPinIcon,
  PlusIcon,
  CheckCircleIcon,
} from '@heroicons/react/24/outline';

interface AddressSelectorProps {
  selectedAddress?: Address;
  onAddressSelect: (address: Address) => void;
}

export default function AddressSelector({ selectedAddress, onAddressSelect }: AddressSelectorProps) {
  const { user: authUser } = useAuth();
  const userPhone = authUser?.phone || 'Phone Not on File'; // Fallback if phone is not available
  const toast = useToast();

  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const [formData, setFormData] = useState({
    name: '',
    street: '',
    apartment: '',
    city: '',
    state: '',
    zipCode: '',
  });

  const loadUserData = useCallback(async () => {
    if (!authUser?.uid) return;
    try {
      setIsLoading(true);
      const userData = await getUserById(authUser.uid);
      setUser(userData);

      // Auto-select default address if no address is selected
      if (!selectedAddress && userData?.addresses && userData.addresses.length > 0) {
        const defaultAddress = userData.addresses.find(a => a.isDefault) || userData.addresses[0];
        onAddressSelect(defaultAddress);
      }
    } catch (error) {
      console.error('Error loading user data:', error);
      toast?.error('Failed to load addresses');
    } finally {
      setIsLoading(false);
    }
  }, [authUser, selectedAddress, onAddressSelect, toast]);

  useEffect(() => {
    if (authUser?.uid) {
      loadUserData();
    }
  }, [authUser, loadUserData]);

  const handleOpenModal = () => {
    setFormData({
      name: '',
      street: '',
      apartment: '',
      city: '',
      state: '',
      zipCode: '',
    });
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setFormData({
      name: '',
      street: '',
      apartment: '',
      city: '',
      state: '',
      zipCode: '',
    });
  };

  const handleSaveAddress = async () => {
    // Validation
    if (!formData.name || !formData.street || !formData.city || !formData.state || !formData.zipCode ) {
      toast?.error('Please fill in all required fields');
      return;
    }

    try {
      setIsSaving(true);

      // Geocode the address to get coordinates
      const coordinates = await geocodeAddress({
        street: formData.street,
        apartment: formData.apartment,
        city: formData.city,
        state: formData.state,
        zipCode: formData.zipCode,
      });

      // Add new address - only include coordinates if geocoding succeeded
      const newAddress: Address = {
        id: '', // Will be generated by service
        ...formData,
        isDefault: user?.addresses?.length === 0,
        ...(coordinates && { coordinates }), // Only include coordinates if not null
      };

      // The service may not return the updated user, so don't assume a return value.
      await addUserAddress(authUser!.uid, newAddress);
      toast?.success('Address added successfully');

      // Fetch the updated user and find the newly added address (it will be the last one)
      const updatedUser = await getUserById(authUser!.uid);
      const addresses = updatedUser?.addresses || [];
      const addedAddress = addresses[addresses.length - 1];

      // Auto-select the newly added address
      if (addedAddress) {
        onAddressSelect(addedAddress);
      }

      await loadUserData();
      handleCloseModal();
    } catch (error) {
      console.error('Error saving address:', error);
      toast?.error('Failed to save address');
    } finally {
      setIsSaving(false);
    }
  };

  const handleSelectAddress = (addressId: string) => {
    const address = user?.addresses?.find(a => a.id === addressId);
    if (address) {
      onAddressSelect(address);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-8">
        <LoadingSpinner size="md" />
      </div>
    );
  }

  const addresses = user?.addresses || [];
  const hasAddresses = addresses.length > 0;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900">Delivery Address</h3>
        {hasAddresses && (
          <Button
            variant="ghost"
            size="sm"
            onClick={handleOpenModal}
            leftIcon={<PlusIcon className="w-4 h-4" />}
          >
            Add New
          </Button>
        )}
      </div>

      {hasAddresses ? (
        <div className="space-y-4">
          {/* Dropdown for address selection */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Select Address
            </label>
            <select
              value={selectedAddress?.id || ''}
              onChange={(e) => handleSelectAddress(e.target.value)}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500 transition-colors"
            >
              <option value="">Choose an address...</option>
              {addresses.map((address) => (
                <option key={address.id} value={address.id}>
                  {address.name}
                  {address.isDefault ? ' (Default)' : ''}
                </option>
              ))}
            </select>
          </div>

          {/* Display selected address details */}
          {selectedAddress && (
            <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
              <div className="flex items-start gap-3">
                <MapPinIcon className="w-5 h-5 text-gray-400 mt-0.5 flex-shrink-0" />
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    <h4 className="font-semibold text-gray-900">{selectedAddress.name}</h4>
                    {selectedAddress.isDefault && (
                      <Badge variant="success" size="sm">
                        Default
                      </Badge>
                    )}
                  </div>
                  <div className="text-sm text-gray-600 space-y-1">
                    <p>{selectedAddress.street}</p>
                    {selectedAddress.apartment && <p>Apt {selectedAddress.apartment}</p>}
                    <p>
                      {selectedAddress.city}, {selectedAddress.state} {selectedAddress.zipCode}
                    </p>
                    <p>{userPhone}</p>
                  </div>
                </div>
                <CheckCircleIcon className="w-6 h-6 text-green-600 flex-shrink-0" />
              </div>
            </div>
          )}
        </div>
      ) : (
        /* No addresses - show prompt to add */
        <div className="bg-gray-50 border-2 border-dashed border-gray-300 rounded-lg p-8 text-center">
          <MapPinIcon className="w-12 h-12 text-gray-400 mx-auto mb-3" />
          <h4 className="text-lg font-semibold text-gray-900 mb-2">No saved addresses</h4>
          <p className="text-gray-600 mb-4">Add a delivery address to continue</p>
          <Button onClick={handleOpenModal} leftIcon={<PlusIcon className="w-5 h-5" />}>
            Add Delivery Address
          </Button>
        </div>
      )}

      {/* Add Address Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={handleCloseModal}
        title="Add New Address"
      >
        <div className="space-y-4">
          <Input
            label="Address Name"
            placeholder="e.g., Home, Work, etc."
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            required
          />

          <Input
            label="Street Address"
            placeholder="123 Main St"
            value={formData.street}
            onChange={(e) => setFormData({ ...formData, street: e.target.value })}
            required
          />

          <Input
            label="Apartment, Suite, etc. (Optional)"
            placeholder="Apt 4B"
            value={formData.apartment}
            onChange={(e) => setFormData({ ...formData, apartment: e.target.value })}
          />

          <div className="grid grid-cols-2 gap-4">
            <Input
              label="City"
              placeholder="New York"
              value={formData.city}
              onChange={(e) => setFormData({ ...formData, city: e.target.value })}
              required
            />

            <Input
              label="State"
              placeholder="NY"
              value={formData.state}
              onChange={(e) => setFormData({ ...formData, state: e.target.value })}
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <Input
              label="ZIP Code"
              placeholder="10001"
              value={formData.zipCode}
              onChange={(e) => setFormData({ ...formData, zipCode: e.target.value })}
              required
            />
          </div>

          <div className="flex gap-3 pt-4">
            <Button
              variant="outline"
              onClick={handleCloseModal}
              className="flex-1"
              disabled={isSaving}
            >
              Cancel
            </Button>
            <Button
              onClick={handleSaveAddress}
              className="flex-1"
              loading={isSaving}
            >
              Add Address
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
