'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { useAuth } from '@/lib/contexts/AuthContext';
import { useRouter } from 'next/navigation';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import Modal from '@/components/ui/Modal';
import Badge from '@/components/ui/Badge';
import LoadingSpinner from '@/components/ui/LoadingSpinner';
import { useToast } from '@/components/ui';
import {
  getUserById,
  addUserAddress,
  updateUserAddress,
  deleteUserAddress,
  setDefaultAddress
} from '@/services/user-service';
import { User, Address } from '@/types/user';
import {
  MapPinIcon,
  PlusIcon,
  PencilIcon,
  TrashIcon,
  CheckCircleIcon,
} from '@heroicons/react/24/outline';

export default function AddressesPage() {
  const { user: authUser, isAuthenticated, loading: authLoading } = useAuth();
  const { showToast } = useToast();
  const router = useRouter();

  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingAddress, setEditingAddress] = useState<Address | null>(null);
  const [isSaving, setIsSaving] = useState(false);

  const [formData, setFormData] = useState({
    name: '',
    street: '',
    apartment: '',
    city: '',
    state: '',
    zipCode: '',
  });

  useEffect(() => {
    if (!authLoading && !isAuthenticated) {
      router.push('/login');
    }
  }, [authLoading, isAuthenticated, router]);

  const loadUserData = useCallback(async () => {
    if (!authUser?.uid) return;
    try {
      setIsLoading(true);
      const userData = await getUserById(authUser.uid);
      setUser(userData);
    } catch (error) {
      console.error('Error loading user data:', error);
      showToast('Failed to load addresses', 'error');
    } finally {
      setIsLoading(false);
    }
  }, [authUser, showToast]);

  useEffect(() => {
    if (authUser?.uid) {
      loadUserData();
    }
  }, [authUser, loadUserData]);

  const handleOpenModal = (address?: Address) => {
    if (address) {
      setEditingAddress(address);
      setFormData({
        name: address.name,
        street: address.street,
        apartment: address.apartment || '',
        city: address.city,
        state: address.state,
        zipCode: address.zipCode,
      });
    } else {
      setEditingAddress(null);
      setFormData({
        name: '',
        street: '',
        apartment: '',
        city: '',
        state: '',
        zipCode: '',
      });
    }
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setEditingAddress(null);
    setFormData({
      name: '',
      street: '',
      apartment: '',
      city: '',
      state: '',
      zipCode: '',
    });
  };

  const handleSaveAddress = async () => {
    // Validation
    if (!formData.name || !formData.street || !formData.city || !formData.state || !formData.zipCode) {
      showToast('Please fill in all required fields', 'error');
      return;
    }

    try {
      setIsSaving(true);

      if (editingAddress) {
        // Update existing address
        await updateUserAddress(authUser!.uid, editingAddress.id, formData);
        showToast('Address updated successfully', 'success');
      } else {
        // Add new address
        const newAddress: Address = {
          id: '', // Will be generated by service
          ...formData,
          isDefault: user?.addresses?.length === 0,
        };
        await addUserAddress(authUser!.uid, newAddress);
        showToast('Address added successfully', 'success');
      }

      await loadUserData();
      handleCloseModal();
    } catch (error) {
      console.error('Error saving address:', error);
      showToast('Failed to save address', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteAddress = async (addressId: string) => {
    if (!confirm('Are you sure you want to delete this address?')) {
      return;
    }

    try {
      await deleteUserAddress(authUser!.uid, addressId);
      showToast('Address deleted successfully', 'success');
      await loadUserData();
    } catch (error) {
      console.error('Error deleting address:', error);
      showToast('Failed to delete address', 'error');
    }
  };

  const handleSetDefault = async (addressId: string) => {
    try {
      await setDefaultAddress(authUser!.uid, addressId);
      showToast('Default address updated', 'success');
      await loadUserData();
    } catch (error) {
      console.error('Error setting default address:', error);
      showToast('Failed to update default address', 'error');
    }
  };

  if (authLoading || isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <LoadingSpinner size="lg" />
      </div>
    );
  }

  if (!user) {
    return (
      <div className="text-center py-12">
        <p className="text-gray-500">User not found</p>
      </div>
    );
  }

  const addresses = user.addresses || [];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white rounded-lg shadow p-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">My Addresses</h1>
            <p className="text-gray-600 mt-1">Manage your delivery addresses</p>
          </div>
          <Button
            onClick={() => handleOpenModal()}
            leftIcon={<PlusIcon className="w-5 h-5" />}
          >
            Add Address
          </Button>
        </div>
      </div>

      {/* Addresses List */}
      {addresses.length === 0 ? (
        <Card>
          <div className="p-12 text-center">
            <MapPinIcon className="w-16 h-16 text-gray-400 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-900 mb-2">No addresses yet</h3>
            <p className="text-gray-600 mb-6">Add your first delivery address to get started</p>
            <Button onClick={() => handleOpenModal()}>
              Add Address
            </Button>
          </div>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {addresses.map((address) => (
            <Card key={address.id} hover>
              <div className="p-6">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <MapPinIcon className="w-5 h-5 text-gray-400" />
                    <h3 className="font-semibold text-gray-900">{address.name}</h3>
                  </div>
                  {address.isDefault && (
                    <Badge variant="success" size="sm">
                      Default
                    </Badge>
                  )}
                </div>

                <div className="text-sm text-gray-600 space-y-1 mb-4">
                  <p>{address.street}</p>
                  {address.apartment && <p>Apt {address.apartment}</p>}
                  <p>
                    {address.city}, {address.state} {address.zipCode}
                  </p>
                </div>

                <div className="flex items-center gap-2">
                  {!address.isDefault && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleSetDefault(address.id)}
                      leftIcon={<CheckCircleIcon className="w-4 h-4" />}
                    >
                      Set Default
                    </Button>
                  )}
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleOpenModal(address)}
                    leftIcon={<PencilIcon className="w-4 h-4" />}
                  >
                    Edit
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleDeleteAddress(address.id)}
                    leftIcon={<TrashIcon className="w-4 h-4" />}
                  >
                    Delete
                  </Button>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}

      {/* Add/Edit Address Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={handleCloseModal}
        title={editingAddress ? 'Edit Address' : 'Add New Address'}
      >
        <div className="space-y-4">
          <Input
            label="Address Name"
            placeholder="e.g., Home, Work, etc."
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            required
          />

          <Input
            label="Street Address"
            placeholder="123 Main St"
            value={formData.street}
            onChange={(e) => setFormData({ ...formData, street: e.target.value })}
            required
          />

          <Input
            label="Apartment, Suite, etc. (Optional)"
            placeholder="Apt 4B"
            value={formData.apartment}
            onChange={(e) => setFormData({ ...formData, apartment: e.target.value })}
          />

          <div className="grid grid-cols-2 gap-4">
            <Input
              label="City"
              placeholder="New York"
              value={formData.city}
              onChange={(e) => setFormData({ ...formData, city: e.target.value })}
              required
            />

            <Input
              label="State"
              placeholder="NY"
              value={formData.state}
              onChange={(e) => setFormData({ ...formData, state: e.target.value })}
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <Input
              label="ZIP Code"
              placeholder="10001"
              value={formData.zipCode}
              onChange={(e) => setFormData({ ...formData, zipCode: e.target.value })}
              required
            />
          </div>

          <div className="flex gap-3 pt-4">
            <Button
              variant="outline"
              onClick={handleCloseModal}
              className="flex-1"
              disabled={isSaving}
            >
              Cancel
            </Button>
            <Button
              onClick={handleSaveAddress}
              className="flex-1"
              loading={isSaving}
            >
              {editingAddress ? 'Update Address' : 'Add Address'}
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
